app/urls.py
from django.urls import path 
from . import views 
 
app_name = 'app' 
urlpatterns = [
    path('', views.index, name='index'), 
    path('admin/', views.admin, name='admin'),
    path('adminestudiante/', views.adminestudiante, name='adminestudiante'),
    path('adminestudiante/crear/', views.adminestudiantecrear, name='adminestudiantecrear'),
    path('editarestudiante/<int:id>/', views.editarestudiante, name='editarestudiante'),
    path('admingrupo/', views.admingrupo, name='admingrupo'),
    path('admingrupo/crear/', views.admingrupocrear, name='admingrupocrear'),
    path('adminvergrupo/<int:id>/', views.adminvergrupo, name='adminvergrupo'),
    path('admineditargrupo/<int:id>/', views.admineditargrupo, name='admineditargrupo'),
    path('eliminarestudiante/<int:id>/', views.eliminarestudiante, name= 'eliminarestudiante'),
    path('agregarestudiante/<int:id>/', views.agregarestudiante, name= 'agregarestudiante'),
    path('adminagregarestudiantegrupo/<int:id>/', views.adminagregarestudiantegrupo, name= 'adminagregarestudiantegrupo'),
    path('adminprofesores/', views.adminprofesores, name='adminprofesores'),
    path('adminprofesores/crear/', views.adminprofesorescrear, name='adminprofesorescrear'),
    path('admineditestu/<int:id>/', views.admineditestu, name='admineditestu'),
    path('adminverprofesor/<int:id>/', views.adminverprofesor, name='adminverprofesor'),
    path('profesor/', views.profesor, name='profesor'),
    path('profveract/', views.profveract, name='profveract'),
    path('profveract/crear/', views.profveractcrear, name='profveractcrear'),
    path('veractividad/<int:id>/', views.veractividad, name='veractividad'),
    path('profnota/<int:id1>/<int:id2>/', views.profnota, name='profnota'),
    path('guardarnota/<int:id1>/<int:id2>/', views.guardarnota, name='guardarnota'),
    path('estudiantes/', views.estudiantes, name='estudiantes'),
    path('estugrupo/<int:id>/', views.estugrupo, name='estugrupo'),
    path('proflistagrupos/', views.proflistagrupos, name='proflistagrupos'),
    path('profactgrupo/', views.profactgrupo, name='profactgrupo'),
    path('profvergrupo/<int:id>/', views.profvergrupo, name='profvergrupo'),
    path('profeactynota/<int:id>', views.profeactynota, name='profeactynota'), 
    path('login/', views.form_login, name='form_login'),
    path('iniciar_sesion/', views.iniciar_sesion, name="iniciar_sesion"),
    path('logout/', views.cerrar_sesion, name='cerrar_sesion'),

]

pelis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('app/', include('app.urls')),

    path('admin/', admin.site.urls),
]

app/templates/app/admin.html
{% load static %}

<html>

<head>
    <title>Administrador</title>
    <link rel="stylesheet" href="{% static 'app/css/admin.css'%}" >
    
    <meta charset="UTF-8">
</head>

<body>
    <div class="contenedor">
        <div class="cabeza">
            <div class="logousta"><img src="{% static 'app/img/logousta.png'%}"/></div>
            <a style="margin-left: 1240;  font-size: medium ; color: white;" >{{ request.user.username}}</a>
            <br>
            <a id="sesion" href="{% url 'app:cerrar_sesion' %}">Cerrar sesión</a>
        </div>
        <div class="contenido">
        
            
            <div class="admest" >
                <a href= "{% url 'app:adminestudiante' %}"><img src="{% static 'app/img/Admest.PNG'%}"></a>
                <a id="click" style="margin-left: 135px;" href="{% url 'app:adminestudiante' %}">Estudiantes</a>
            </div>

            <div class="admgrup">
                <a href="{% url 'app:admingrupo' %}"><img src="{% static 'app/img/Admgrup.PNG'%}"></a>
                <a id="click" style="margin-left: 150px;" href= "{% url 'app:admingrupo' %}">Grupos</a>
            </div>

            <div class="admprof">
                <a href="{% url 'app:adminprofesores' %}"><img src="{% static 'app/img/Admprof.PNG'%}"></a>
                <a id="click" style="margin-left: 150px;" href="{% url 'app:adminprofesores' %}">Profesores</a>
            </div>
            
        </div>
    </div>
</body>
</html>

app/templates/app/adminagregarestudiantegrupo.html
{% extends "app/adminestudiante.html" %}
{% block contenido %}

  <div >
        <form action= "{% url 'app:agregarestudiante' idgrupo%}" method="POST">

          {% csrf_token %}
        <h1 style="color: #244f92; margin-left: 35px">Estudiantes</h1>

        {% if estudiantes %}
        <table>
            <tr>
              <th>Nombre</th>
              <th>Apellido</th>
              <th>codigo</th>
              <th>ID</th>
              <th></th>
            </tr>
            {% for estudiante in estudiantes %}
            <tr>
              <td> {{ estudiante.estudiante.user.first_name }}  </td>
              <td> {{ estudiante.estudiante.user.last_name }}  </td>
              <td> {{ estudiante.estudiante.codigo }}  </td>
              <td> {{ estudiante.id }}  </td>
              <td> <a href= "{% url 'app:eliminarestudiante' estudiante.id %}">
                Eliminar
            </a>  </td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <h1>No hay Estudiantes</h1>
        {% endif %}


        <br />
        <label >Estudiantes</label>

        <select name="estudianteselect" style="height:30px ; background: rgb(197, 245, 245); margin-left: 50px;" >
          {% for estudiante in estudiantes_todos %}
          
          <option value="{{estudiante.user.id}}">{{estudiante.user.username}}</option>
          {% endfor %}
      </select>
        <input id ="btnagregarest" type="submit" style="height: 30px; width: 150px; color: white;" value="Agregar">
      </form>
  </div>

    
{% endblock %}

app/templates/app/admineditestu.html
{% extends "app/adminestudiante.html" %} 
{% block contenido %}
<div class="editar"> 
  <h1>Estudiante</h1>
  <form action= "{% url 'app:editarestudiante' info_estudiante.user_id%}" method="POST">

    {% csrf_token %}

    <label for="">Nombre</label>
    <input type="text" size="30" name="nombre" class="input-texto" value=" {{ info_estudiante.user.first_name }} "/>
    <br />
    <br />
    <label for="">Apellido</label>
    <input type="text" size="30" name="apellido" class="input-texto" value=" {{ info_estudiante.user.last_name }} " />
    <br />
    <br /> 
    <label for="">Usuario</label>
    <input type="text" size="30" name="usuario" class="input-texto" value=" {{ info_estudiante.user.username }} " />
    <br />
    <br /> 
    <label for="">Email</label>
    <input
      type="email"
      size="30"
      class="input-texto"
      style="margin-left: 18px"
      name="email"
      value=" {{ info_estudiante.user.email }}"
    />
    <br />
    <br />
    <label for="">Código</label>
    <input type="text" size="30" class="input-texto" style="margin-left: 6px" name="codigo" value=" {{ info_estudiante.codigo }} " />
    <br />
    <br />
    
    <input
      id="btnguardar"
      type="submit"
      style="height: 30px; width: 150px"
      value="Guardar"
    />
  </form>
</div>
{% endblock %}

app/templates/app/adminprofesores.html
{% extends "app/adminestudiante.html" %} 
{% block contenido %}

<form action= "{% url 'app:adminprofesorescrear' %}" method="POST" >

    {% csrf_token %}

        <div class="formulario">
            <div class="area1">
                <h1 style="color:#244f92;">Profesores</h1>
                    <label for="">Nombres</label>
                    <input type="text"  size="30" class="input-texto" name="nombre" >
                    <br>
                    <br>
                    <label for="">Apellidos</label>
                    <input type="text" size="30" class="input-texto " name="apellido" >
                    <br>
                    <br>
                    <label for="">Email</label>
                    <input type="email" size="30" class="input-texto" style=" margin-left: 18px; " name="email">
            </div> 
            <div class="area2">
                <label for="">Cátedra</label>
                <input type="checkbox" size="30" style=" margin-left: 18px; " name="catedra">
                <br>
                <br>
                <label for="">Documento</label>
                <input type="text" class="input-texto" name="documento" size="30" style=" margin-left: 53px; " name="documento" >
                <br>
                <br>
                <label for="">Nombre de usuario</label>
                <input type="text" class="input-texto" name="username" size="30" name="username" >
                <br>
                <input id ="btningresar" type="submit" style="height: 30px; width: 150px;" value="Crear Profesor">
                <br><br>


            </div>

        </div>
        <div class="tabla"> 
            <h1 style="color: #244f92; margin-left: 35px;">Lista de Profesores</h1>
        
            {% if prof_list %}
        <table>
            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Email</th>
            </tr>
            {% for profesor in prof_list %}
            <tr>
              <td> {{ profesor.user.first_name }}  </td>
              <td> {{ profesor.user.last_name }}  </td>
              <td> {{ profesor.user.email }}  </td>
              <td><a href= "{% url 'app:adminverprofesor' profesor.user_id %}">
                ver
            </a></td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <h1>No hay grupos</h1>
        {% endif %}

        </div>

    </form>
{% endblock %}

app/templates/app/adminvergrupo.html
{% extends "app/adminestudiante.html" %} 
{% block contenido %}

<form action= "{% url 'app:admineditargrupo' grupo.id %}" method="POST">

  {% csrf_token %}
<div class="formulario">
            <div class="area1">
            <h1 style="color: #244f92">Grupo</h1>
           
           
            <label class="label2" style="margin-left: 100px;"></label>
            <br />
            <br />
            <label for="">Código de grupo</label>
            <input
            name="codigo"
              type="text"
              size="30"
              class="input-texto"
              value=" {{ grupo.codigo }} "
            />
            <br />
            <br /> 
            <label for="">Asignatura</label>
            <input
              type="text"
              size="30"
              class="input-texto"
              name="asignatura"
              style=" 
                margin-left: 40px;
              "
              value=" {{ grupo.asignatura }} "
            /> <br><br>
            <a href= "{% url 'app:adminagregarestudiantegrupo' grupo.id %}" style="margin-left: 40;">Ver estudiantes</a>
          </div>
          <div class="area2" style="margin-left: 50px; " >
            <br />
            <br />
            <label for="">*Profesor</label>
                    <select name="profesor" style="height:30px ; background: rgb(197, 245, 245); margin-left: 50px;" >
                        {% for profesor in profesores %}
                        <option value="{{profesor.user_id}}">{{profesor.user.username}}</option>
                        {% endfor %} 
                    </select>
            <br /><br />
            <label for="">Semestre</label>
            <input
              type="text"
              size="30"
              name="semestre"
              style="
                height: 30px;
                background: rgb(197, 245, 245);
                margin-left: 22px;
              "
              value=" {{ grupo.semestre }} "
            />
            <br /><br />
            <input id ="btnguardargrup" type="submit" style="height: 30px; width: 150px; margin-left: 160px; color: white;" value="Guardar">
          </div>
        </div>
      </form>



{% endblock %}

app/templates/app/adminverprofesor.html
{% extends "app/adminestudiante.html" %} 
{% block contenido %}
        <form>
        <div class="formulario">
            <div class="area1">
                <h1 style="color:#244f92;">Profesor</h1>
                    <label for="">Nombres</label>
                    <label class="label2" style="margin-left: 5px;" for="">{{ profesor.user.first_name }}</label><br> <br>
                    <label for="">Apellidos</label>
                    <label class="label2" style="margin-left: 5px;" for="">{{ profesor.user.last_name }}</label><br> <br>
                    <label for="">Email</label>
                    <label class="label2" style="margin-left: 32px;" for="">{{ profesor.user.email }}</label><br> <br>
            </div>

        </div>
        <div class="tabla">
            <h1 style="color: #244f92; margin-left: 35px;">Lista de Grupos</h1>

            {% if grupos %}
            <table> 
                <tr>
                    <th>Semestre</th>
                    <th>Código</th>
                    <th>Asignatura</th>
                    <th>No. de estudiantes</th>
                </tr>
                {% for grupos in grupos %}
                <tr>
                  <td> {{ grupos.semestre }}  </td>
                  <td> {{ grupos.codigo }}  </td>
                  <td> {{ grupos.asignatura }}  </td>
                  <td> {{ grupos.id }}  </td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
            <h1>No hay profesores</h1>
            {% endif %}

        </div>

    </form>

{% endblock %}

app/templates/app/estudiantes.html
{% load static %}

<html lang="en">
<head>
    <title>Estudiante</title>
    <link rel="stylesheet" href="{% static 'app/css/ver.css'%}">
    <meta charset="UTF-8">
</head>
<body>

    <div class="contenedor">
        <div class="cabeza">
             <div class="logousta"><img src="{% static 'app/img/logousta.png'%}" /></div>
             <a style="margin-left: 1240;  font-size: medium ; color: white;" >{{ request.user.username}}</a>
            <a id="sesion2" href="{% url 'app:cerrar_sesion' %}">Cerrar sesión</a>
        </div>
        <form>
        <div class="formulario">
            <div class="area1">
                <h1 style="color:#244f92;  ">{{ request.user.username}} </h1>
                
                
                    <label for="">Nombre</label>
                    <label class="label2" >{{request.user.first_name}}</label>
                    <br>
                    <br>
                    <label >Apellido</label>
                    <label class="label2" >{{request.user.last_name}}</label>
                    <br><br>
                    <label >Email</label>
                    <label class="label2" style="margin-left: 55px;" >{{request.user.email}}</label>
                    <br><br>
                    <label >Código</label>
                    <label class="label2" style="margin-left: 45px;" >{{request.user.estudiante.codigo}}</label>

                
            </div> 
            <div class="area2">
                
            </div>

        </div>
        <div class="tabla">
            <h1>Mis grupos</h1>

            {% if grupos %}
          <table>
            <tr>
                <th>Asignatura</th>
                <th>Semestre</th>
                <th>ID del grupo</th>
                <th>   </th>
            </tr>
            {% for grupo in grupos %}
            <tr>
              <td> {{ grupo.grupo.asignatura}}  </td>
              <td> {{ grupo.grupo.semestre }}  </td>
              <td> {{ grupo.grupo.id }}  </td>
              <td> 
                <a href="{% url 'app:estugrupo' grupo.id %}">
                  Ver </a >
              </td>

            </tr>
            {% endfor %}
          </table>
          {% else %}
          <h1>No hay Grupos</h1>
          {% endif %}


        </div>
    </form>



    </div>
    
</body>
</html>

app/templates/app/estugrupo.html
{% load static %}

<html lang="en">
<head>
    <title>Grupo</title>
    <link rel="stylesheet" href="{% static 'app/css/ver.css'%}">
    <meta charset="UTF-8">
</head>
<body>

    <div class="contenedor">
        <div class="cabeza">
            <div class="logousta"><img src="{% static 'app/img/logousta.png'%}" /></div>
            <a style="margin-left: 1240;  font-size: medium ; color: white;" >{{ request.user.username}}</a>
            <a id="inicio" href="{% url 'app:estudiantes' %}">Inicio |</a>
            <a id="sesion" href="{% url 'app:index' %}">Cerrar sesión</a>
        </div>
        <form>
        <div class="formulario"> 
            <div class="area1">
                <h1>{{ grupo.grupo.asignatura }}</h1>
                <div class="divfondo">
                    <label >Código del grupo</label>
                    <label class="label2" style="margin-left: 15px;" >{{ grupo.grupo.codigo }}</label>
                    <br>
                    <br>
                    <label >Semestre</label>
                    <label class="label2" style="margin-left: 50px;" >{{ grupo.grupo.semestre }}</label>
                    <br>
                    <br>
                    <label >Profesor</label>
                    <label class="label2" style="margin-left: 65px;" >{{grupo.grupo.profesor.user.username}}</label>
                    </div>
                </div>

        <div class="tabla">
            <h1 style="color: #244f92; margin-left: 35px;">Lista de Actividades</h1>
            
            {% if actividades %}
          <table>
            <tr>
                <th>Descripción</th>
                <th>Fecha de entrega</th>
            </tr>
            {% for actividad in actividades %}
            <tr>
              <td> {{ actividad.descripcion}}  </td>
              <td> {{ actividad.fecha_creacion}}  </td>
            </tr>
            {% endfor %}
          </table>
          {% else %}
          <h1>No hay Actividades</h1>
          {% endif %}


            <h1 style="color: #244f92; margin-left: 35px;">Lista de Notas</h1>
            
            {% if notas %}
          <table>
            <tr>
                <th>Actividad</th>
                <th>Fecha de entrega</th>
            </tr>
            {% for nota in notas %}
            <tr>
              <td> {{ nota.actividad.descripcion}}  </td>
              <td> {{ nota.valor}}  </td>
            </tr>
            {% endfor %}
          </table>
          {% else %}
          <h1>No hay notas registradas</h1>
          {% endif %}
        </div>

        </div>
    </form>



    </div>
    
</body>
</html>

app/templates/app/index.html
{% load static %}


<html>
  <head>
    <title>Inicio</title>
    <link rel="stylesheet" href="{% static 'app/css/index.css'%}" >
    <meta charset="UTF-8">
  </head>

  <body>

    <div class="contenedor">
      <div class="cabeza">
        <div class="logousta"><img src="{% static 'app/img/logousta.png'%}" /></div>
      </div>
      
      <div
        style="background-image: url( app/static/app/img/fondoinicio.jpg)"
        class="contenido"
      >
        <div class="imagenestu"><img src="{% static 'app/img/estudiantes.jpg'%}" /></div>

        <div class="iniciar">
          <h1>Accede a la plataforma</h1>
          <form action= "{% url 'app:iniciar_sesion'  %}" method="POST" >

            {% csrf_token %}

            
             <label for="">Nombre de usuario</label>
             <input type="text" size=45 name="username" style="height: 25px;">
             <label for="">Contraseña</label>
             <input type="password" size="45" name="password" style="height: 25px;">
             <input id ="btningresar" type="submit" style="height: 30px; width: 100px;" value="Ingresar">
            {% if error %}
             <span class="error">{{error}}</span>
            {% endif %}
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

app/templates/app/profactgrupo.html
{% extends "app/profveract.html" %} 
{% block contenido %}
      <form>
        <div class="formulario">
          <div class="area1">
              <br><br>
          </div>
        </div>
      

      <div class="tabla">
        <h1 style="color: #244f92; margin-left: 35px">Lista de Grupos</h1>

        {% if proflista_grupos %} 
        <table>
            <tr>
              <th>Grupo</th>
              <th>Asignatura</th> 
              <th>Semestre</th>
              <th> </th>
              
            </tr>
            {% for grupo in proflista_grupos %}
            <tr>
              <td> {{ grupo.codigo }}  </td>
              <td> {{ grupo.asignatura }}  </td>
              <td> {{ grupo.semestre }}  </td>
              <td> 
                <a href= "{% url 'app:profveract' grupo.id %}"> 
                  agregar actividad
                </a>
                
              </td>
              
            {% endfor %}
        </table>
        {% else %}
        <h1>No hay Grupos</h1>
        {% endif %}

       

    </form>
    {% endblock %}

app/templates/app/profesor.html
{% load static %}
<html>

<head>
    <title>Profesor</title>
    <link rel="stylesheet" href="{% static 'app/css/admin.css'%}" />
    <meta charset="UTF-8">
</head>

<body>
    <div class="contenedor">
        <div class="cabezaprof">
            <div class="logousta"><img src="{% static 'app/img/logousta.png'%}"/></div>
            <a id="sesion" href="{% url 'app:cerrar_sesion' %}">Cerrar sesión</a>
        </div>
        <div class="contenido">

            <div class="admest" style="margin-left: 150px;">
                <a class="aest" href="{% url 'app:profveract' %}"><img src="{% static 'app/img/Admest.PNG'%}"></a>
                <a id="click" style="margin-left: 140px;" href="{% url 'app:profveract' %}">Actividades</a>
            </div> 

            <div class="admgrup" style="margin-left:220px;">
                <a href="{% url 'app:proflistagrupos' %}"><img src="{% static 'app/img/Admgrup.PNG'%}"></a>
                <a id="click" style="margin-left: 160px;" href="{% url 'app:proflistagrupos' %}">Grupos</a>
            </div>
            
        </div>
    </div>
</body>
</html>

app/templates/app/proflistagrupos.html
{% extends "app/profveract.html" %} 
{% block contenido %}
      <form>
        <div class="formulario">
          <div class="area1">
              <br><br>
          </div>
        </div>
      

      <div class="tabla">
        <h1 style="color: #244f92; margin-left: 35px">Lista de Grupos</h1>

        {% if proflista_grupos %}
        <table>
            <tr>
              <th>Grupo</th>
              <th>Asignatura</th>
              <th>Semestre</th>
              <th> </th>
              
            </tr>
            {% for grupo in proflista_grupos %}

            <tr>
              <td> {{ grupo.codigo }}  </td>
              <td> {{ grupo.asignatura }}  </td>
              <td> {{ grupo.semestre }}  </td>
              <td> 
                <a href= "{% url 'app:profvergrupo' grupo.id %}">
                  ver
                </a>
                
              </td>
              
            {% endfor %} 
        </table>
        {% else %}
        <h1>No hay Grupos</h1>
        {% endif %}

       

    </form>
    {% endblock %}

app/templates/app/profveract.html
{% load static %}

<html lang="en">
  <head>
    <title>Actividad</title>
    <link rel="stylesheet" href="{% static 'app/css/ver.css'%}" />
    <meta charset="UTF-8">
  </head>
  <body>
    <div class="contenedor">
        <div class="cabezaprof">
          <div class="logousta"><img src="{% static 'app/img/logousta.png'%}" /></div>
          <a style="margin-left: 1240;  font-size: medium ; color: white;" >{{ request.user.username}}</a>
          <a id="inicio" href="{% url 'app:profesor' %}">Inicio |</a>
          <a id="sesion" href="{% url 'app:index' %}">Cerrar sesión</a>
        </div>
        
        {% block contenido %}
        <form action= "{% url 'app:profveractcrear'  %}" method="POST" >

          {% csrf_token %}

        <div class="formulario">
          <div class="area1">
            <h1>Actividades</h1>

            <label for="">Grupo</label>
                    <select name="grupo" style="height:30px ; background: rgb(197, 245, 245); margin-left: 50px;" >
                        {% for grupo in grupos %}
                        <option value="{{grupo.id}}">{{grupo.asignatura}}</option>
                        {% endfor %} 
                    </select>

            <br><br>


            <label for="">Descripción</label>
            <input
              type="text"
              size="50"
              class="input-texto"
              style="height: 100px; margin-left: 10px;"
              name="descripcion"
            />
          </div>  
          <div class="area2">
            <label for="">Fecha de entrega</label>
            <input
              type="date"
              class="input-texto"
              style="margin-left: 18px"
              name="fecha"
            /> <br><br>
            <input
              id="btningresar"
              type="submit"
              style="height: 30px; width: 150px"
              value="Crear actividad"
            />
          </div>
        </div>
        <div class="tabla">
          <h1 >
            Lista de Actividades
          </h1>
          {% if actividades %}
          <table>
            <tr>
              <th>Grupo</th>
              <th>Asignatura</th>
              <th>Descripción</th>
              <th>Fecha de entrega</th>
              <th>Profesor</th>
              <th>ID</th>
              
            </tr>
            {% for acti in actividades %}

            {% if request.user.username == acti.grupo.profesor.user.username %}
            <tr>
              <td> {{ acti.grupo.codigo }}  </td>
              <td> {{ acti.grupo.asignatura }}  </td>
              <td> {{ acti.descripcion }}  </td>
              <td> {{ acti.fecha_creacion }}  </td>
              <td> {{ acti.grupo.profesor.user.username }}  </td>
              <td> {{ acti.id }} 
            </tr>
            {% endif %}
            {% endfor %}
          </table>
          {% else %}
          <h1>No hay Estudiantes</h1>
          {% endif %}

          
          
        </div>
      </form>
      {% endblock %}
    </div>
  </body>
</html>

app/templates/app/profvergrupo.html
{% extends "app/profveract.html" %} 
{% block contenido %}

      <form>
        <div class="formulario">
          <div class="area1">
            <h1>{{ info_grupo.asignatura}}</h1>
            <br>
            <label >Código</label>
            <label class="label2" style="margin-left: 60px;" >{{ info_grupo.codigo }}</label><br> <br>
            <label >Semestre</label>
            <label class="label2" style="margin-left: 35px;" >{{ info_grupo.semestre}}</label><br> <br>
            
          </div>
        </div>
      

      <div class="tabla">

        <h1>Estudiantes</h1>
        {% if estudiantes %} 
        <table>
            <tr>
              <th>Nombre</th>
              <th>Apellido</th>
              <th>codigo</th>
              <th>  </th>
              
            </tr>
            {% for estudiante in estudiantes %}
            <tr>
              <td> {{ estudiante.estudiante.user.first_name}}  </td>
              <td> {{ estudiante.estudiante.user.last_name}}  </td>
              <td> {{ estudiante.estudiante.codigo}}  </td>
              <td> 
                <a href= "{% url 'app:profeactynota' estudiante.id %}">
                  ver
                </a>
              </td>
              
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <h1>No hay Estudiantes</h1>
        {% endif %}

        <h1>Actividades</h1>
        {% if actividades %}
          <table>
            <tr>
              <th>Grupo</th>
              <th>Asignatura</th>
              <th>Descripción</th>
              <th>Fecha de entrega</th>
              <th>ID</th>
              <th>  </th>
            </tr>
            {% for actividad in actividades %}
            <tr>
              <td> {{ actividad.grupo }}  </td>
              <td> {{ actividad.grupo.asignatura }}  </td>
              <td> {{ actividad.descripcion }}  </td>
              <td> {{ actividad.fecha_creacion }}  </td>
              <td> {{ actividad.id }}
              <td> 
                <a href="{% url 'app:veractividad' actividad.id %}">
                  Ver </a >
              </td>

            </tr>
            {% endfor %}
          </table>
          {% else %}
          <h1>No hay Actividades</h1>
          {% endif %}

    </form>
    {% endblock %}